lsi: false
safe: true
source: [docs/]
incremental: false
highlighter: rouge
gist:
  noscript: false
markdown: kramdown
remote_theme: benbalter/retlab
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge