title: CCRP notes
author:
  name: Knud Nor Nielsen
  email: knn@plen.ku.dk
description: > # this means to ignore newlines until "show_excerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

show_excerpts: false # set to true to show excerpts on the homepage

collections:
  action:

lsi: false
safe: true
source: [docs/]
incremental: false
highlighter: rouge
gist:
  noscript: false
markdown: kramdown
remote_theme: benbalter/retlab
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge